image: gradle:7-jdk17

services:
  - name: docker:26.1.2-dind
    alias: docker
    command: ["--tls=false"]

variables:
  # Instruct Testcontainers to use the daemon of DinD, use port 2375 for non-tls connections.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

stages:
  - test-docker
  - test

test-docker:
  allow_failure: true
  image: docker:24.0.5-dind
  stage: test-docker
  script:
    - docker image ls
    - docker container ls
  only:
  - main

test:
  stage: test
  script:
    - ./gradlew test --info
  only:
  - main
