image: gradle:7-jdk17

services:
  - name: docker:24.0.5-dind
    alias: docker

stages:
  - test-docker
  - test

test-docker:
  stage: test-docker
  script:
    - docker image ls
    - docker container ls
  only:
  - main

test:
  stage: test
  script:
    - ./gradlew test --info
  only:
  - main
