image: gradle:7-jdk17

services:
  - name: docker:26.1.2-dind
    alias: docker

variables:
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""

stages:
  - test-docker
  - test
  - test-docker-after

test-docker-before:
  allow_failure: true
  image: docker:24.0.5-dind
  stage: test-docker
  script:
    - docker image ls
    - docker container ls
  only:
  - main

test:
  stage: test
  script:
    - ./gradlew test --info
  only:
  - main

test-docker-after:
  allow_failure: true
  image: docker:24.0.5-dind
  stage: test-docker-after
  script:
    - docker image ls
    - docker container ls
  only:
  - main
